SELECT DISTINCT CNAME
FROM CUSTOMERS
WHERE CNAME = (

SELECT DISTINCT C.CNAME
FROM CUSTOMERS C
JOIN ORDERS O ON(C.CNO = O.CNO)
JOIN ODETAILS D ON(O.ONO = D.ONO)
JOIN PARTS P ON(D.PNO = P.PNO)
WHERE ALL(p.price <= 20.00)
)
